package ch.heigvd.hbcg;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hakim
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carte1 = new javax.swing.JLabel();
        carte2 = new javax.swing.JLabel();
        carte3 = new javax.swing.JLabel();
        carte4 = new javax.swing.JLabel();
        carte5 = new javax.swing.JLabel();
        pos1 = new javax.swing.JLabel();
        pos2 = new javax.swing.JLabel();
        pos3 = new javax.swing.JLabel();
        pos4 = new javax.swing.JLabel();
        pos5 = new javax.swing.JLabel();
        pos6 = new javax.swing.JLabel();
        pos7 = new javax.swing.JLabel();
        pos8 = new javax.swing.JLabel();
        pos9 = new javax.swing.JLabel();
        pos10 = new javax.swing.JLabel();
        background_table = new javax.swing.JLabel();
        messageToSend = new javax.swing.JTextField();
        messageToDisplay = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        b_suivre = new javax.swing.JButton();
        b_seCoucher = new javax.swing.JButton();
        b_miser = new javax.swing.JButton();
        slider_miser = new javax.swing.JSlider();
        background_frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 1500));
        setPreferredSize(new java.awt.Dimension(1003, 860));
        getContentPane().setLayout(null);

        carte1.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\resizedEtArrondie\\final\\1_trefle.png")); // NOI18N
        carte1.setMaximumSize(new java.awt.Dimension(100, 70));
        carte1.setMinimumSize(new java.awt.Dimension(100, 70));
        carte1.setPreferredSize(new java.awt.Dimension(100, 70));
        getContentPane().add(carte1);
        carte1.setBounds(340, 200, 70, 90);

        carte2.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\resizedEtArrondie\\final\\2_trefle.png")); // NOI18N
        carte2.setText("jLabel2");
        getContentPane().add(carte2);
        carte2.setBounds(395, 200, 70, 90);

        carte3.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\resizedEtArrondie\\final\\3_trefle.png")); // NOI18N
        getContentPane().add(carte3);
        carte3.setBounds(450, 200, 70, 90);

        carte4.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\resizedEtArrondie\\final\\4_trefle.png")); // NOI18N
        getContentPane().add(carte4);
        carte4.setBounds(505, 200, 70, 90);

        carte5.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\resizedEtArrondie\\final\\5_trefle.png")); // NOI18N
        getContentPane().add(carte5);
        carte5.setBounds(560, 200, 70, 90);

        pos1.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\oval.png")); // NOI18N
        pos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos1MouseReleased(evt);
            }
        });
        getContentPane().add(pos1);
        pos1.setBounds(810, 120, 90, 80);

        pos2.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\oval.png")); // NOI18N
        getContentPane().add(pos2);
        pos2.setBounds(840, 230, 90, 80);

        pos3.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\oval.png")); // NOI18N
        getContentPane().add(pos3);
        pos3.setBounds(810, 340, 90, 80);

        pos4.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\oval.png")); // NOI18N
        getContentPane().add(pos4);
        pos4.setBounds(710, 420, 90, 80);

        pos5.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\oval.png")); // NOI18N
        getContentPane().add(pos5);
        pos5.setBounds(560, 430, 90, 80);

        pos6.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\oval.png")); // NOI18N
        getContentPane().add(pos6);
        pos6.setBounds(380, 430, 90, 80);

        pos7.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\oval.png")); // NOI18N
        getContentPane().add(pos7);
        pos7.setBounds(210, 420, 90, 80);

        pos8.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\oval.png")); // NOI18N
        getContentPane().add(pos8);
        pos8.setBounds(90, 360, 90, 80);

        pos9.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\oval.png")); // NOI18N
        getContentPane().add(pos9);
        pos9.setBounds(40, 240, 90, 80);

        pos10.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\oval.png")); // NOI18N
        getContentPane().add(pos10);
        pos10.setBounds(60, 120, 90, 80);

        background_table.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\poker_table.png")); // NOI18N
        getContentPane().add(background_table);
        background_table.setBounds(110, -70, 970, 620);
        background_table.getAccessibleContext().setAccessibleName("background");

        messageToSend.setText("Saisissez votre texte ici...");
        getContentPane().add(messageToSend);
        messageToSend.setBounds(0, 770, 500, 50);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jTextArea1.setHighlighter(null);
        messageToDisplay.setViewportView(jTextArea1);

        getContentPane().add(messageToDisplay);
        messageToDisplay.setBounds(0, 570, 500, 200);

        b_suivre.setText("Suivre");
        b_suivre.setMaximumSize(new java.awt.Dimension(85, 23));
        b_suivre.setMinimumSize(new java.awt.Dimension(85, 23));
        b_suivre.setPreferredSize(new java.awt.Dimension(85, 23));
        getContentPane().add(b_suivre);
        b_suivre.setBounds(830, 620, 110, 23);

        b_seCoucher.setText("Se coucher");
        getContentPane().add(b_seCoucher);
        b_seCoucher.setBounds(590, 620, 130, 23);

        b_miser.setText("Miser");
        b_miser.setMaximumSize(new java.awt.Dimension(85, 23));
        b_miser.setMinimumSize(new java.awt.Dimension(85, 23));
        b_miser.setPreferredSize(new java.awt.Dimension(85, 23));
        getContentPane().add(b_miser);
        b_miser.setBounds(720, 620, 110, 23);

        slider_miser.setMaximumSize(new java.awt.Dimension(255, 26));
        slider_miser.setMinimumSize(new java.awt.Dimension(255, 26));
        slider_miser.setPreferredSize(new java.awt.Dimension(255, 26));
        getContentPane().add(slider_miser);
        slider_miser.setBounds(590, 640, 350, 26);

        background_frame.setIcon(new javax.swing.ImageIcon("D:\\Bureau\\HEIG-VD\\2eme\\2eme_semestre\\GEN\\PROJET_OFFICIEL\\poker\\src\\main\\resources\\background_fond.png")); // NOI18N
        background_frame.setText("jLabel6");
        getContentPane().add(background_frame);
        background_frame.setBounds(-5, -6, 990, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pos1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos1MouseReleased
            // TODO add your handling code here:
            System.out.print("prout");
    }//GEN-LAST:event_pos1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_miser;
    private javax.swing.JButton b_seCoucher;
    private javax.swing.JButton b_suivre;
    private javax.swing.JLabel background_frame;
    private javax.swing.JLabel background_table;
    private javax.swing.JLabel carte1;
    private javax.swing.JLabel carte2;
    private javax.swing.JLabel carte3;
    private javax.swing.JLabel carte4;
    private javax.swing.JLabel carte5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane messageToDisplay;
    private javax.swing.JTextField messageToSend;
    private javax.swing.JLabel pos1;
    private javax.swing.JLabel pos10;
    private javax.swing.JLabel pos2;
    private javax.swing.JLabel pos3;
    private javax.swing.JLabel pos4;
    private javax.swing.JLabel pos5;
    private javax.swing.JLabel pos6;
    private javax.swing.JLabel pos7;
    private javax.swing.JLabel pos8;
    private javax.swing.JLabel pos9;
    private javax.swing.JSlider slider_miser;
    // End of variables declaration//GEN-END:variables
}
