package ch.heigvd.hbcg;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hakim
 */
public class NewJFrame extends JFrame implements UserInterface {

    private PokerPlayer pokerPlayer;

    /**
     * Creates new form NewJFrame
     */
   /* public NewJFrame() {
        initComponents();
    }*/

    public NewJFrame(PokerPlayer pokerPlayer) {

        if(pokerPlayer != null){

            initComponents();
            this.pokerPlayer = pokerPlayer;
            pokerPlayer.setUserInterface(this);
            //initComponents();
            this.setVisible(true);
            System.out.println("New frame de " + pokerPlayer.getPseudo());
        }

    }

    @Override
    public void display(PokerItem pokerItem){
        //this.pokerItem = pokerItem;
       // messageToSend.setText(pokerItem.toString());
        System.out.println("DISPLAY SUR FENETRE");
        messageArea.append(pokerItem.toString() + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carte1 = new javax.swing.JLabel();
        carte2 = new javax.swing.JLabel();
        carte3 = new javax.swing.JLabel();
        carte4 = new javax.swing.JLabel();
        carte5 = new javax.swing.JLabel();
        pos1 = new javax.swing.JLabel();
        pos2 = new javax.swing.JLabel();
        pos3 = new javax.swing.JLabel();
        pos4 = new javax.swing.JLabel();
        pos5 = new javax.swing.JLabel();
        pos6 = new javax.swing.JLabel();
        pos7 = new javax.swing.JLabel();
        pos8 = new javax.swing.JLabel();
        pos9 = new javax.swing.JLabel();
        pos10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        croupier = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        background_table = new javax.swing.JLabel();
        b_sendMessage = new javax.swing.JLabel();
        messageToSend = new javax.swing.JTextField();
        messageToDisplay = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        b_suivre = new javax.swing.JButton();
        b_seCoucher = new javax.swing.JButton();
        b_miser = new javax.swing.JButton();
        valueSlider = new javax.swing.JTextField();
        slider_miser = new javax.swing.JSlider();
        montant_mise = new javax.swing.JLabel();
        background_frame = new javax.swing.JLabel();

        setResizable(false);
        setMaximumSize(new Dimension(1500,1500));
        setPreferredSize(new Dimension(1003,1000));
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);




        carte1.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\final\\1_trefle.png")); // NOI18N
        carte1.setMaximumSize(new java.awt.Dimension(100, 70));
        carte1.setMinimumSize(new java.awt.Dimension(100, 70));
        carte1.setPreferredSize(new java.awt.Dimension(100, 70));
        getContentPane().add(carte1);
        carte1.setBounds(360, 350, 70, 90);

        carte2.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\final\\2_trefle.png")); // NOI18N
        carte2.setText("jLabel2");
        getContentPane().add(carte2);
        carte2.setBounds(420, 350, 70, 90);

        carte3.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\final\\3_trefle.png")); // NOI18N
        getContentPane().add(carte3);
        carte3.setBounds(470, 350, 70, 90);

        carte4.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\final\\4_trefle.png")); // NOI18N
        getContentPane().add(carte4);
        carte4.setBounds(530, 350, 70, 90);

        carte5.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\final\\5_trefle.png")); // NOI18N
        getContentPane().add(carte5);
        carte5.setBounds(580, 350, 70, 90);

        pos1.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\oval.png")); // NOI18N
        pos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos1MouseReleased(evt);
            }
        });
        getContentPane().add(pos1);
        pos1.setBounds(830, 260, 90, 80);

        pos2.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\oval.png")); // NOI18N
        pos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos2MouseReleased(evt);
            }
        });
        getContentPane().add(pos2);
        pos2.setBounds(860, 370, 90, 80);

        pos3.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\oval.png")); // NOI18N
        pos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos3MouseReleased(evt);
            }
        });
        getContentPane().add(pos3);
        pos3.setBounds(830, 480, 90, 80);

        pos4.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\oval.png")); // NOI18N
        pos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos4MouseReleased(evt);
            }
        });
        getContentPane().add(pos4);
        pos4.setBounds(720, 570, 90, 80);

        pos5.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\oval.png")); // NOI18N
        pos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos5MouseReleased(evt);
            }
        });
        getContentPane().add(pos5);
        pos5.setBounds(580, 570, 90, 80);

        pos6.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\oval.png")); // NOI18N
        pos6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos6MouseReleased(evt);
            }
        });
        getContentPane().add(pos6);
        pos6.setBounds(400, 570, 90, 80);

        pos7.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\oval.png")); // NOI18N
        pos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos7MouseReleased(evt);
            }
        });
        getContentPane().add(pos7);
        pos7.setBounds(230, 560, 90, 80);

        pos8.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\oval.png")); // NOI18N
        pos8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos8MouseReleased(evt);
            }
        });
        getContentPane().add(pos8);
        pos8.setBounds(110, 500, 90, 80);

        pos9.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\oval.png")); // NOI18N
        pos9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos9MouseReleased(evt);
            }
        });
        getContentPane().add(pos9);
        pos9.setBounds(60, 380, 90, 80);

        pos10.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\oval.png")); // NOI18N
        pos10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pos10MouseReleased(evt);
            }
        });
        getContentPane().add(pos10);
        pos10.setBounds(80, 260, 90, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 530, 70, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 520, 70, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(810, 450, 70, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(790, 440, 70, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(830, 350, 70, 70);

        jLabel9.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(810, 340, 70, 70);

        jLabel10.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(810, 220, 70, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(790, 210, 70, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(390, 530, 70, 70);

        jLabel13.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(370, 520, 70, 70);

        jLabel14.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(220, 520, 70, 70);

        jLabel15.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 510, 70, 70);

        jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(100, 470, 70, 70);

        jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(80, 460, 70, 70);

        jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(50, 350, 70, 70);

        jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 340, 70, 70);

        jLabel20.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(70, 220, 70, 70);

        jLabel21.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(50, 210, 70, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 540, 70, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\resizedEtArrondie\\output-onlinepngtools (1).png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 530, 70, 70);

        croupier.setForeground(new java.awt.Color(255, 255, 255));
        croupier.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\croupier.png")); // NOI18N
        getContentPane().add(croupier);
        croupier.setBounds(460, 170, 70, 80);

        logo.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Logos\\final\\allSizes\\medium.png")); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(400, 30, 200, 162);
        getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(480, 710, 20, 200);

        background_table.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\poker_table.png")); // NOI18N
        getContentPane().add(background_table);
        background_table.setBounds(130, 80, 970, 620);
        background_table.getAccessibleContext().setAccessibleName("background");

        b_sendMessage.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\send.png")); // NOI18N
        b_sendMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_sendMessageMouseClicked(evt);
            }
        });
        getContentPane().add(b_sendMessage);
        b_sendMessage.setBounds(440, 915, 30, 40);

        messageToSend.setText("Saisissez votre texte ici...");
        messageToSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                messageToSendMouseReleased(evt);
            }
        });
        messageToSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                messageToSendKeyPressed(evt);
            }
        });
        getContentPane().add(messageToSend);
        messageToSend.setBounds(0, 910, 500, 50);

        messageArea.setEditable(false);
        messageArea.setColumns(20);
        messageArea.setRows(5);
        messageArea.setFocusable(false);
        messageArea.setHighlighter(null);
        messageToDisplay.setViewportView(messageArea);

        getContentPane().add(messageToDisplay);
        messageToDisplay.setBounds(0, 710, 500, 200);

        b_suivre.setText("Suivre");
        b_suivre.setMaximumSize(new java.awt.Dimension(85, 23));
        b_suivre.setMinimumSize(new java.awt.Dimension(85, 23));
        b_suivre.setPreferredSize(new java.awt.Dimension(85, 23));
        getContentPane().add(b_suivre);
        b_suivre.setBounds(830, 770, 110, 23);

        b_seCoucher.setText("Se coucher");
        b_seCoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seCoucherActionPerformed(evt);
            }
        });
        getContentPane().add(b_seCoucher);
        b_seCoucher.setBounds(590, 770, 130, 22);

        b_miser.setText("Miser");
        b_miser.setMaximumSize(new java.awt.Dimension(85, 23));
        b_miser.setMinimumSize(new java.awt.Dimension(85, 23));
        b_miser.setPreferredSize(new java.awt.Dimension(85, 23));
        b_miser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_miserActionPerformed(evt);
            }
        });
        getContentPane().add(b_miser);
        b_miser.setBounds(720, 770, 110, 23);

        valueSlider.setMaximumSize(new java.awt.Dimension(85, 23));
        valueSlider.setMinimumSize(new java.awt.Dimension(85, 23));
        valueSlider.setPreferredSize(new java.awt.Dimension(85, 23));
        valueSlider.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valueSliderFocusLost(evt);
            }
        });
        valueSlider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueSliderActionPerformed(evt);
            }
        });
        valueSlider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                valueSliderPropertyChange(evt);
            }
        });
        getContentPane().add(valueSlider);
        valueSlider.setBounds(720, 830, 100, 30);

        slider_miser.setMaximumSize(new java.awt.Dimension(255, 26));
        slider_miser.setMinimumSize(new java.awt.Dimension(255, 26));
        slider_miser.setPreferredSize(new java.awt.Dimension(255, 26));
        slider_miser.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_miserStateChanged(evt);
            }
        });
        getContentPane().add(slider_miser);
        slider_miser.setBounds(590, 790, 350, 26);

        montant_mise.setForeground(new java.awt.Color(255, 255, 255));
        montant_mise.setText("CHF");
        getContentPane().add(montant_mise);
        montant_mise.setBounds(840, 840, 90, 16);

        background_frame.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\background_fond.png")); // NOI18N
        background_frame.setText("jLabel6");
        background_frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                background_frameMouseReleased(evt);
            }
        });
        getContentPane().add(background_frame);
        background_frame.setBounds(-5, -6, 1000, 970);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pos1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos1MouseReleased
        sitDown(1);
    }//GEN-LAST:event_pos1MouseReleased

    private void slider_miserStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_miserStateChanged
        //@TODO on est obligé de miser au moins 1 fois la big blind, il faut vérifier cela sur le Slider
        valueSlider.setText(String.valueOf(slider_miser.getValue()));
        if(slider_miser.getValue() > 0)
           b_miser.setEnabled(true);
        else
            b_miser.setEnabled(false);
        
    }//GEN-LAST:event_slider_miserStateChanged

    private void pos2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos2MouseReleased
        sitDown(2);
    }//GEN-LAST:event_pos2MouseReleased

    private void pos3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos3MouseReleased
       sitDown(3);
    }//GEN-LAST:event_pos3MouseReleased

    private void pos4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos4MouseReleased
       sitDown(4);
    }//GEN-LAST:event_pos4MouseReleased

    private void pos5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos5MouseReleased
       sitDown(5);
    }//GEN-LAST:event_pos5MouseReleased

    private void pos6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos6MouseReleased
       sitDown(6);
    }//GEN-LAST:event_pos6MouseReleased

    private void pos7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos7MouseReleased
       sitDown(7);
    }//GEN-LAST:event_pos7MouseReleased

    private void pos8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos8MouseReleased
       sitDown(8);
    }//GEN-LAST:event_pos8MouseReleased

    private void pos9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos9MouseReleased
       sitDown(9);
    }//GEN-LAST:event_pos9MouseReleased

    private void pos10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos10MouseReleased
       sitDown(10);
    }//GEN-LAST:event_pos10MouseReleased

    private void b_seCoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seCoucherActionPerformed
        System.out.print("Je me couche par terre!");
    }//GEN-LAST:event_b_seCoucherActionPerformed

    private void b_miserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_miserActionPerformed
        messageArea.setText(messageArea.getText() + "Croupier : Mise de " + valueSlider.getText() + " de l'utilisateur : \n");
    }//GEN-LAST:event_b_miserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jScrollBar1.setValue(100);
        messageArea.setText("Croupier : Bienvenue à la table !\n");
        valueSlider.setText("0");
        slider_miser.setValue(0);
        slider_miser.setMaximum(10000); //@TODO definir le maximum de mise pour chaque table
        b_miser.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void messageToSendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageToSendMouseReleased
        if(messageToSend.getText().equals("Saisissez votre texte ici..."))
            messageToSend.setText("");
    }//GEN-LAST:event_messageToSendMouseReleased

    private void background_frameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_frameMouseReleased
        background_frame.requestFocusInWindow();
    }//GEN-LAST:event_background_frameMouseReleased

    private void valueSliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_valueSliderPropertyChange

    }//GEN-LAST:event_valueSliderPropertyChange

    private void valueSliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueSliderActionPerformed
     if(!valueSlider.getText().equals("")) {
            slider_miser.setValue(Integer.valueOf(valueSlider.getText()));
            if(Integer.valueOf(valueSlider.getText()) > 0)
                b_miser.setEnabled(true);
            else
                b_miser.setEnabled(false);
            System.out.print(Integer.valueOf(valueSlider.getText()));

        }    }//GEN-LAST:event_valueSliderActionPerformed

    private void valueSliderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valueSliderFocusLost
    if(!valueSlider.getText().equals("")) {
            slider_miser.setValue(Integer.valueOf(valueSlider.getText()));
                    
            System.out.print(Integer.valueOf(valueSlider.getText()));

        }
    }//GEN-LAST:event_valueSliderFocusLost

    private void messageToSendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageToSendKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
              submitMessage();
        }
    }//GEN-LAST:event_messageToSendKeyPressed

    private void b_sendMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_sendMessageMouseClicked
        submitMessage();
    }//GEN-LAST:event_b_sendMessageMouseClicked
    
    public void submitMessage() {
        String message = messageToSend.getText();
        if(!message.isEmpty()) {

            messageArea.setText(messageArea.getText() + pokerPlayer.getPseudo() + ": " + message + "\n");
            messageToSend.setText("");
            pokerPlayer.send(message);
        }
    }
    
    public void sitDown(int position) {
        System.out.print(position);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    /*    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });*/
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_miser;
    private javax.swing.JButton b_seCoucher;
    private javax.swing.JLabel b_sendMessage;
    private javax.swing.JButton b_suivre;
    private javax.swing.JLabel background_frame;
    private javax.swing.JLabel background_table;
    private javax.swing.JLabel carte1;
    private javax.swing.JLabel carte2;
    private javax.swing.JLabel carte3;
    private javax.swing.JLabel carte4;
    private javax.swing.JLabel carte5;
    private javax.swing.JLabel croupier;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JScrollPane messageToDisplay;
    private javax.swing.JTextField messageToSend;
    private javax.swing.JLabel montant_mise;
    private javax.swing.JLabel pos1;
    private javax.swing.JLabel pos10;
    private javax.swing.JLabel pos2;
    private javax.swing.JLabel pos3;
    private javax.swing.JLabel pos4;
    private javax.swing.JLabel pos5;
    private javax.swing.JLabel pos6;
    private javax.swing.JLabel pos7;
    private javax.swing.JLabel pos8;
    private javax.swing.JLabel pos9;
    private javax.swing.JSlider slider_miser;
    private javax.swing.JTextField valueSlider;

    // End of variables declaration//GEN-END:variables
}
